baseURL: https://diopmagatte.github.io
languageCode: en-us
title: "Magatte DIOP | Security Analyst"
theme: toha

languages:
  en:
    languageName: English
    weight: 1
  fr:
    languageName: Français
    weight: 2

outputs:
  home:
    - HTML
    - RSS
    - JSON

enableEmoji: true
enableRobotsTXT: true

markup:
  goldmark:
    renderer:
      unsafe: true

params:
  background: /images/background.jpg
  gitRepo: https://github.com/diopmagatte/diopmagatte.github.io
  features:
    portfolio:
      enable: true
    blog:
      enable: false
  footer:
    enable: true